server:
  servlet:
    context-path: /ms-data-master-account/api/v1
  port: 8080

spring:
  application:
    name: ms-data-master-account
  datasource:
    url: jdbc:postgresql://172.96.190.219:5432/sequrra-db?currentSchema=ms-data-master-account
    username: postgres
    password: Cl100299
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      idle-timeout: 300000
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # Adjust this according to your needs
      max-request-size: 20MB

  flyway:
    url: jdbc:postgresql://localhost:5432/sequrra-db?currentSchema=ms-data-master-account
    user: postgres
    password: Cl100299
    schemas: ms-data-master-account
    baseline-on-migrate: true
    enabled: true
    validate-on-migrate: true
    baseline-version: 1.1
    locations: classpath:db/migration
    out-of-order: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

  mail:
    host: mail.privateemail.com
    port: 465
    username: info@ugkslimousine.com
    password: Kowping.8888
    protocol: smtp
    properties:
      mail:
        smpt:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 140965361707-ggcluflva9ma8qgjf1ko0kl9a41o006a.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

common:
  pageable:
    size: 100
    page: 0
  sorting: ASC

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

oss:
  endpoint: https://ap-south-1.linodeobjects.com
  secret-key: Tcoz4fHXQVpctEm4mLApofuua9GkmUHhPYpYS6DB
  access-key: 5Q6I158TPIDBOLAAB2V0
  bucket: ugks-oss


endpoint:
  authentication:
    base: /authentication
    signup: /signup
    login: /login
    refresh-token: /refresh-token
    forgot-password: /forgot-password
    reset-password: /reset-password
    oauth-google: /oauth-google


#kafka:
#  producer:
#    bootstrap-servers: 139.162.36.148:9093
#    key-serializer: org.apache.kafka.common.serialization.StringSerializer
#    value-serializer: org.apache.kafka.common.serialization.StringSerializer
#  topics:
#      - name: account.auth.events
#        num-partitions: 3
#        replication-factor: 1